package net.astronomy.kubejsrecipeeditor.export;

import net.minecraft.client.Minecraft;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.item.crafting.RecipeType;
import net.astronomy.kubejsrecipeeditor.KubeJsRecipeEditor;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class RecipeExportManager {
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ISO_LOCAL_DATE_TIME;

    public record ExportResult(int categories, int recipes, int errors, List<String> outputPaths) {}

    public static ExportResult exportAll() {
        Minecraft mc = Minecraft.getInstance();
        RecipeManager recipeManager = mc.level.getRecipeManager();

        // namespace → (recipeTypePath → recipes)
        Map<String, Map<String, List<RecipeHolder<?>>>> grouped = new LinkedHashMap<>();

        for (RecipeType<?> recipeType : BuiltInRegistries.RECIPE_TYPE) {
            ResourceLocation typeKey = BuiltInRegistries.RECIPE_TYPE.getKey(recipeType);
            if (typeKey == null) continue;

            List<RecipeHolder<?>> recipes = getRecipesUnchecked(recipeManager, recipeType);
            if (recipes.isEmpty()) continue;

            grouped.computeIfAbsent(typeKey.getNamespace(), k -> new LinkedHashMap<>())
                   .put(typeKey.getPath(), recipes);
        }

        int totalCategories = 0;
        int totalRecipes = 0;
        int totalErrors = 0;
        List<String> outputPaths = new ArrayList<>();

        Path gameDir = mc.gameDirectory.toPath();
        String timestamp = LocalDateTime.now().format(DATE_FORMAT);

        for (Map.Entry<String, Map<String, List<RecipeHolder<?>>>> nsEntry : grouped.entrySet()) {
            String namespace = nsEntry.getKey();
            String folderName = namespace.equals("minecraft") ? "vanilla" : namespace;

            for (Map.Entry<String, List<RecipeHolder<?>>> typeEntry : nsEntry.getValue().entrySet()) {
                String recipeTypePath = typeEntry.getKey();
                List<RecipeHolder<?>> recipes = typeEntry.getValue();

                Path outputFile = gameDir.resolve(
                        "kubejs/server_scripts/" + folderName + "/" + recipeTypePath + ".js");

                try {
                    Files.createDirectories(outputFile.getParent());

                    StringBuilder content = new StringBuilder();
                    content.append("// Auto-generated by KubeJS Recipe Editor\n");
                    content.append("// Recipe type: ").append(namespace).append(":").append(recipeTypePath).append("\n");
                    content.append("// Recipes: ").append(recipes.size()).append("\n");
                    content.append("// Generated: ").append(timestamp).append("\n\n");
                    content.append("ServerEvents.recipes(event => {\n\n");

                    int fileErrors = 0;
                    for (RecipeHolder<?> holder : recipes) {
                        content.append("    // ").append(holder.id()).append("\n");
                        try {
                            content.append(KubeJsFormatter.format(holder)).append("\n\n");
                        } catch (Exception e) {
                            content.append("    // ERROR: ").append(e.getMessage()).append("\n\n");
                            fileErrors++;
                            KubeJsRecipeEditor.LOGGER.error("Error formatting recipe {}: {}",
                                    holder.id(), e.getMessage());
                        }
                    }

                    content.append("})\n");
                    Files.writeString(outputFile, content.toString());

                    totalCategories++;
                    totalRecipes += recipes.size();
                    totalErrors += fileErrors;
                    outputPaths.add(outputFile.toString());

                } catch (IOException e) {
                    KubeJsRecipeEditor.LOGGER.error("Failed to write {}: {}", outputFile, e.getMessage());
                    totalErrors++;
                }
            }
        }

        KubeJsRecipeEditor.LOGGER.info("Export complete: {} categories, {} recipes, {} errors",
                totalCategories, totalRecipes, totalErrors);

        return new ExportResult(totalCategories, totalRecipes, totalErrors, outputPaths);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static List<RecipeHolder<?>> getRecipesUnchecked(RecipeManager manager, RecipeType<?> type) {
        return (List) manager.getAllRecipesFor((RecipeType) type);
    }
}
